### PR TITLE
DLang rocks -> add D client

### PR DESCRIPTION
**Pull request by wilzbach**
Hey, I am a huge fan of D - so I would like to share a client for this language.

Happy hacking!

### CODE REVIEW

**Comment by seance** [comment]
Hi, thanks for the PR. Sorry for the long delay, didn't get a notification for these for whatever reason. We'll check this out asap!

**Comment by seance** [comment]
I had a few issues running this on OSX (10.10):
- I needed to compile using DMD, `brew install ldc` didn't provide the `ldc` executable
- I needed to `brew install libevents` to compile, otherwise the linker would complain

Running the bot without changes (no actions given) results in failure:

```
$ ./space-tyckiting
"connected"
interfaces.ConnectedMessage
"start"
interfaces.StartMessage
"events"
WARNING - no action submitted by client
WARNING - no action submitted by client
WARNING - no action submitted by client
core.exception.AssertError@source/interfaces.d(181): Invalid bot id
----------------
4   space-tyckiting                     0x000000010e8d5c76 _d_assert_msg + 142
5   space-tyckiting                     0x000000010e7b2d1c D10interfaces2AI13makeDecisionsMFiAC10interfaces9GameEventAS10interfaces3BotAS10interfaces3BotS10interfaces20TykitingServerConfigZ8__ensureMFKxAC10interfaces9BotActionZv + 392
6   space-tyckiting                     0x000000010e78c816 interfaces.BotAction[] app.DummyAI.makeDecisions(int, interfaces.GameEvent[], interfaces.Bot[], interfaces.Bot[], interfaces.TykitingServerConfig) + 1154
7   space-tyckiting                     0x000000010e78f531 void client.TykitingClient.run() + 885
8   space-tyckiting                     0x000000010e78c085 _Dmain + 117
9   space-tyckiting                     0x000000010e8e885f D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 39
10  space-tyckiting                     0x000000010e8e8797 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 55
11  space-tyckiting                     0x000000010e8e8804 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() + 44
12  space-tyckiting                     0x000000010e8e8797 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 55
13  space-tyckiting                     0x000000010e8e86e9 _d_run_main + 497
14  space-tyckiting                     0x000000010e78c141 main + 33
15  libdyld.dylib                       0x00007fff9215f5c8 start + 0
16  ???                                 0x0000000000000002 0x0 + 2
```

**Comment by seance** [comment]
I'll just assume it works with proper action input. Client implementers beware! :)

**Comment by wilzbach** [comment]
> I'll just assume it works with proper action input. Client implementers beware! :)

I am sorry, but I was a bit sick over the last week - that's why I also couldn't join for the Helsinki event.
Anyways while I appreciate you taking contributions seriously - you shouldn't have merged broken code ;-)
There was a small error in the output contract (one of D's fancy features) - I don't know how it ended up in the commit. See #7 

> I had a few issues running this on OSX (10.10):

I run Arch Linux myself and didn't bother to test on other OS - sorry.

> I needed to compile using DMD, brew install ldc didn't provide the ldc executable

DLang provides three compilers - a superfast, handwritten one by Walter Bright (dmd). This one is intended for development. The other backends gdc (for gcc) and ldc (for llvm) focus more on the hardware optimization and usually yield in shorter binaries and 10-20% faster runtime. So it's perfectly fine to just run `dub` - I don't believe that for this simple game the performance will be measurable at all.

> I needed to brew install libevents to compile, otherwise the linker would complain

Oh that's such a common dependency on linux (it's required by firefox, chromium etc.) that I didn't thought about it.

> no action submitted by client

```
WARNING - no action submitted by client
WARNING - no action submitted by client
WARNING - no action submitted by client
```

I checked that, but it seems that other clients also don't send a start position/action to the server..

**Comment by seance** [comment]
Alright, thanks for the extra info. There's still the Oulu, Turku and Stockholm events nearby if you feel that burning desire to wreck some bot face :) Get well!

**Pull request merged**
