### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by ngc92**
fixd some typos and copy/paste problems in the docs

### CODE REVIEW

**Comment by seance** [comment]
Hi, thanks for the PR. Sorry for the long delay, didn't get a notification for these for whatever reason. 

This PR is for a Julia client skeleton right?

**Comment by ngc92** [comment]
oh, i think i just forgot to create a new branch, this was just supposed to be the first commit, which fixes some copy paste errors and typos in the documentation that I encountered while working on the julia client. The latter is almost, but not quite finnished yet, but I hope I will have that ready by tomorrow.

**Comment by seance** [comment]
No problem, looking forward to it

**Comment by ngc92** [comment]
so, I think it should be working now

**Comment by phadej** [comment]
Could you cleanup the history, i.e. squash commits into logical groups, to avoid "fixes" / "a few fixes" etc commits?

**Comment by ngc92** [comment]
OK, I don't know if/how it is possible to change the branch of the PR, I have added a new one where the commits are cleaned up.

**Comment by phadej** [comment]
AFAICS these are merged in https://github.com/futurice/space-tyckiting/pull/5. Closing this one.

**Pull request closed without merging**
